Added correct configuration for mac

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -34,33 +34,53 @@ function yum_based(){
 	done
 }
 
-printf "Checking libraries...\n"
+function brew_based(){
+        packages=(pcre openssl libssh)
+        for i in "${packages[@]}"
+        do
+                printf "Checking package: ${i}\t"
+                brew list &> /dev/null
+                if [ "$?" != "0" ];then
+                        printf "Not found\n"
+                        printf "Trying install package: ${i}\n"
+                        brew install "$i"
+                else
+                        printf "Installed\n"
+                fi
+        done
+}
 
-for i in "${libs[@]}"
-do
-	printf "${i}\t"
-	ldconfig -p | grep "${i}" > /dev/null
-	if [ "$?" == "0" ];then
-		printf "Ok\n"
-	else
-		printf "not found\n"
-		error=1
-	fi
-done
-
-[ "$error" != "1" ] && exit;
-
-printf "Checking system...\n"
-
-if [ -n "$(which apt-get)" ];then
-	printf "apt-get based\n";
-	apt_based
-elif [ -n "$(which yum)" ];then
-	printf "yum based\n";
-	yum_based
+if [ -n "$(which brew)" ];then
+	printf "brew based\n";
+	brew_based
 else
-	printf "yum or apt-get not found,\n"
-	printf "you can download and install the following libs:\n"
-	printf "libcurl, libpcre, libssl and libssh\n\n"
-fi
+	printf "Checking libraries...\n"
 
+	for i in "${libs[@]}"
+	do
+		printf "${i}\t"
+		ldconfig -p | grep "${i}" > /dev/null
+		if [ "$?" == "0" ];then
+			printf "Ok\n"
+		else
+			printf "not found\n"
+			error=1
+		fi
+	done
+
+	[ "$error" != "1" ] && exit;
+
+	printf "Checking system...\n"
+
+	if [ -n "$(which apt-get)" ];then
+		printf "apt-get based\n";
+		apt_based
+	elif [ -n "$(which yum)" ];then
+		printf "yum based\n";
+		yum_based
+	else
+		printf "yum or apt-get not found,\n"
+		printf "you can download and install the following libs:\n"
+		printf "libcurl, libpcre, libssl and libssh\n\n"
+	fi
+fi
